name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # packages
      - run: npx lerna bootstrap
      - run: npx lerna run build:ci

      # linting
      - run: npm run lint:prettier
      - run: npm run lint:eslint

      # auditing
      - run: npx license-check --ignoreRegex @nmshd/connector
      # - run: npx better-npm-audit audit --exclude 1004876

      # tests
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npx lerna run test:ci
        env:
          DATABASE_CONNECTION_STRING: mongodb://127.0.0.1:27017/?readPreference=primary&appname=transport&ssl=false
